### ISSUE TITLE
Tool : Suggestions 

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#104]
En vu de remplacer le forum, un module de suggestion et de votes public sur le site

**Comment by Endalaust** [comment]
3 retours + 1 feature request : 

### Bugs

- Le symbole de notification est persistant en haut à droite, même si je n'ai aucune notification. Toutes les notifications cumulées sur les suggestions sont persistantes 

<img width="1425" alt="screenshot_2129" src="https://user-images.githubusercontent.com/1420867/88433062-b24c8280-cdfd-11ea-9089-96f22023e297.png">
 
- Lorsque l'on publie une suggestion, il me semble pertinent de rajouter par défaut le vote de l'auteur 

- La liste des votants ne s'actualise pas bien : Si je suis sur la suggestion et que je vote, mon pseudo n'apparait pas. Si je dévote, mon pseudo ne disparait pas non plus. Pire, si je dévote et que je refresh la page, mon pseudo est toujours là.

### Feature request

Searchbar 
<img width="871" alt="screenshot_2130" src="https://user-images.githubusercontent.com/1420867/88433297-140cec80-cdfe-11ea-8a7d-1b4b1bba57c5.png">

A noter qu'un effet actuel m'échappe : Je suis dans la searchbar et je fais ENTER, me fait apparaitre le bloc filter (wtf)

**Comment by joshwhedon** [comment]
"La suppression d'une suggestion la masque mais conserve la route, je peux continuer à accéder à une suggestion supprimée si j'ai toujours l'URL. Je pense que ce phénomène est industrialisé sur tout le site... Est-il possible de rendre KO la route sur une suppression de contenu type news / event / suggestion ?"
Donc ce que j'ai fait, c'est que le staff peut toujours acceder aux contenus supprimes (news, event, suggestions, etc etc) mais pas les joueurs. LE contenu est soft delete. Avec un joueur normalement tu auras pas acces quand on sera live.

**Comment by Endalaust** [comment]
Le filtre "Tous" ne fonctionne pas

Reproduire : 
Changer le filtre sur "Site"
Revenir sur "Tous"

**Comment by Endalaust** [comment]
Le filtre par défaut sur Tendance ne fonctionne pas non plus, on est sur un filtre par défaut sur "nouveaux" et le filtrage tendance ne fonctionne pas :(

**Comment by Endalaust** [comment]
Je crois que @joshwhedon ne regarde plus mes commentaires :d

**Comment by joshwhedon** [comment]
Ca devrait etre corrige.
