### ISSUE TITLE
Events : Rendre obligatoire de commenter sa note

### ISSUE THREAD

**Issue by KreatorWoE** [way-of-elendil/website#109]
Je trouve qu'il serait fort sympathique de rendre obligatoire de commenter sa note afin d'avoir un retour constructif derrière.

Personnellement c'est ce qui m'intéresse, une critique (positive comme négative) et pas juste une note.

**Comment by joshwhedon** [comment]
Prochaine mise a jour il y aura la liste des votants et la note donnee sur la page des events. On pourra revoir apres si on doit changer un peu, base sur le comportement utilisateur.
Affaire a suivre.
