### ISSUE TITLE
Post récupérations : Alertes

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#124]
### Objectif : Identifier les récupérations après traitement qui seraient possiblement frauduleuses

Business rules : 

- On scan toutes les récupérations passées et validées dans un délai de 3 mois pour populer une table si sur l'IP en jeu du personnage récupéré, on identifie d'autres levels 80
- Est populé dans cette table les personnages 80 concernés, leurs comptes WOW, et l'IP commune

<img width="1228" alt="screenshot_1879" src="https://user-images.githubusercontent.com/1420867/86517693-34fba680-be2b-11ea-80d0-9e5e5dbeea1f.png">

Le maître de jeu mène son enquête pour identifier le cas (abus de confiance ou situation régulière)

Exemple de situation régulière : Famille, le joueur a levelup un 80 entre temps, un ami lui prête son compte à titre exceptionnel. 
Exemple de situation frauduleuse : L'IP des personnages recensés est toujours la même, démontrant une seule et unique personne sur un personnage récupéré avec d'autres 80 en sa possession 

### Given data

Par défaut, les tableaux affichent la data par date de la plus récente à la plus ancienne

Date : date d'insertion du log dans la table
Personnage : Nom du personnage + compte wow du joueur récupéré
Récupéré le : Date de la récupération
80 identifiés : Nom du personnage + compte wow des joueurs 80 identifiés
IP commune : Adresse IP qui a permis cette détection
Traité par : username du maitre de jeu qui a cliqué sur les CTA
CTA : Bouton d'action
Label : Statu du cas remonté

Au clic sur un CTA, la ligne disparait du tableau "Alertes actives" et apparait dans le tableau "Historique"

### Gestion de l'historique

Lorsque le maitre de jeu a identifié le cas, il clique sur le CTA correspondant (sanction ou fausse alerte) pour classer le cas. 

<img width="1240" alt="screenshot_1878" src="https://user-images.githubusercontent.com/1420867/86517656-de8e6800-be2a-11ea-8514-58716e1f8a1e.png">

Il est probable sur des fraudes aux récups qu'on ai 2 logs (ou plus) pour le même cas : Un par personnage récupéré. Au maître de jeu de bien prendre en compte tous les cas et de cliquer sur les boutons d'action.  

### Questions ouvertes

Est-ce utile de rajouter un texte libre ou une liste d'option pour un "motif" qui serait visible dans l'historique ? @Babyface-187 @hermes-gm @Pixel-woe

**Comment by joshwhedon** [comment]
Avoir un champ commentaire se tient oui.
