### ISSUE TITLE
Mises a jour recentes / Changelog

### ISSUE THREAD

**Issue by joshwhedon** [way-of-elendil/website#126]
Ajouter un bouton dans la section administration afin de generer un changelog automatiquement a partir des mises a jours recentes, le poster sur discord, et afficher les changements sur une page du site.

**Comment by joshwhedon** [comment]
Sur web-server, il faut configurer woe.github.user et woe.github.password (avec un compte qui a acces en lecture au repo jeu).
Y'a 2 tables dans web. J'ai ajoute un bouton dans la page d'admin pour generer les maj.
Avant de faire la toute premiere maj, il faut que tu insere dans server_update une ligne avec la date de la derniere maj (uniquement a faire la premiere fois).

**Comment by joshwhedon** [comment]
Je ferai l'integration discord une fois qu'on sera raccord sur l'implementation.

**Comment by Endalaust** [comment]
Magnifique le remplissage de la table
Bien joué l'intégration

Je me note de faire le front

**Comment by Endalaust** [comment]
```
Hi @you,

On July 29th, 2020 at 22:00 (UTC) you used a password to access an endpoint through the GitHub API using GitHubJava/2.1.5:

https://api.github.com/repositories/xxxx

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.

Thanks,
The GitHub Team

```

**Comment by joshwhedon** [comment]
Je change la config. woe.github.token= remplace username et password. 
Il faut generer un token https://github.com/settings/tokens avec les droits repos et mettre le token dans cette nouvelle variable (prochaine maj du webserver)

**Comment by Endalaust** [comment]
Prêt à être utilisé en prod
Pour discord, à faire il me semble
