### ISSUE TITLE
Missions

### ISSUE THREAD

**Issue by joshwhedon** [way-of-elendil/website#142]
Implementation d'un systeme de mission sur le site permettant d'obtenir des recompenses (credits, objets, avatar, etc etc).

Les missions peuvent etre des missions en jeu (champ de bataille, donjon, etc etc) ou sur le site (voter, aimer un post sur facebook, etc).

**Comment by joshwhedon** [comment]
https://way-of-elendil.fr/suggestions/13-missions

**Comment by Endalaust** [comment]
<img width="708" alt="screenshot_2327" src="https://user-images.githubusercontent.com/1420867/90572785-2982f580-e1b5-11ea-8153-39126426495d.png">

La callout success s'affiche lorsque le joueur a cliqué sur le bouton "Récupérer ma récompense" ce qui a pour effet d'enlever la mission de la liste et d'afficher la callout. 

<img width="125" alt="screenshot_2328" src="https://user-images.githubusercontent.com/1420867/90572854-559e7680-e1b5-11ea-9433-813a085a93ab.png">

Il s'agit d'un timer qui affiche le temps restant, différent entre hebdo et journa

<img width="63" alt="screenshot_2329" src="https://user-images.githubusercontent.com/1420867/90572905-7070eb00-e1b5-11ea-92ed-f68b317b3339.png">

L'image sera tirée de woehead. Un champs db avec le nom de l'image sera suffisant, la banque d'images de wow devrait suffire pour nos missions custom non liées au jeu. Inch allah

Si toutes les missions sont faites : 
https://github.com/joshwhedon/angular-website/commit/61c4ba43d89f034f940f4c2585a56bff98b4e7f4#diff-230090e07e7ffb677268b1248474981eR15 
Je suis sur à 100% que ma condition ne marche pas

A été abandonné pour l'instant : 

- L'abandon d'une mission
- Le recycle d'une mission journalière par jour

**Comment by Endalaust** [comment]
<img width="431" alt="screenshot_2330" src="https://user-images.githubusercontent.com/1420867/90573548-f93c5680-e1b6-11ea-87c8-0ec032cd133d.png">
Si 4 missions dispo on affiche un badge 4, si 2 missions dispo badge 2, si 0 mission dispo, aucun badge

**Comment by joshwhedon** [comment]
Pour le badge, ne serait-ce pas interressant d'avoir 2 versions du badge, un vert pour indiquer qu'il y a des missions completes a clamer, et un jaune pour indiquer qu'il y a des missions en cours ?

**Comment by Endalaust** [comment]
Optim en vrac:
- Nouveau compte, 1ere mission = Se connecter au jeu

Pour le badge, why not, est-ce qu'on le découpe en 2 badges ou un seul badge qui change juste de couleur msieur l'UX?
