### ISSUE TITLE
Page profil

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#144]
Mettre en place une page de profil publique du master account

**Comment by joshwhedon** [comment]
https://way-of-elendil.fr/suggestions/8-page-de-profil-de-joueur

**Comment by Endalaust** [comment]
<img width="1282" alt="screenshot_2236" src="https://user-images.githubusercontent.com/1420867/89584416-568dea80-d83c-11ea-940e-a3aadccd5f24.png">

### Header

<img width="338" alt="screenshot_2237" src="https://user-images.githubusercontent.com/1420867/89584488-6f969b80-d83c-11ea-9b6e-5eac9edcda55.png">

Class possibles : 

- GameMaster
- VIP
- MVP

Dernière connexion : Idéalement la date la plus récente sur un compte jeu associé, sinon la date du compte master 
Badge green : Présent idéalement si le joueur est connecté au jeu sur un personnage, sinon pas de badge

### Plus joués

<img width="811" alt="screenshot_2238" src="https://user-images.githubusercontent.com/1420867/89584634-ad93bf80-d83c-11ea-8e96-9195f390bd57.png">

Parmi tous ses personnages on affiche les 4 les plus joués, triés par /played : characters.totalTime

### Type de compte

<img width="373" alt="screenshot_2239" src="https://user-images.githubusercontent.com/1420867/89584741-dfa52180-d83c-11ea-84f3-8af93a966f76.png">

```
<table class="rank">
    <tbody>
        <tr>
            <td class="center">
                <img src="/assets/img/components/Account/normal.png" alt="normal"><br />
                <span class="grey">Normal</span>
            </td>
        </tr>
        <!--
        <tr>
            <td class="center">
                <img src="/assets/img/components/Account/vip.png" alt="vip"><br />
                <span class="purple">VIP</span>
            </td>
        </tr>
        <tr>
            <td class="center">
                <img src="/assets/img/components/Account/mvp.png" alt="mvp"><br />
                <span class="green">MVP</span>
            </td>
        </tr>
        <tr>
            <td class="center">
                <img src="/assets/img/components/GameIcon/blizz_talk_logo.png" alt="mj"><br />
                <span class="GameMaster">Staff</span>
            </td>
        </tr>
        <tr>
            <td>Personnages joués</td>
        </tr>
        -->
    </tbody>
</table>
```

Le MVP n'a pas encore été éclairé, il viendra plus tard.

### Informations

<img width="422" alt="screenshot_2240" src="https://user-images.githubusercontent.com/1420867/89584865-14b17400-d83d-11ea-8425-097da1beef4d.png">

- Sur Elendil depuis : Date la plus ancienne de création de compte parmi tous les comptes jeu associés
- Temps de jeu : Cumul du characters.totalTime pour tous ses personnages en jours
- Personnages joués : Cumul de tous les personnages liés

### Statistiques

<img width="401" alt="screenshot_2241" src="https://user-images.githubusercontent.com/1420867/89584956-44f91280-d83d-11ea-89f1-d667993a92ad.png">

- Hauts-faits de site : Pt de HF de site
- Quêtes de site accomplies : Nombre de quêtes faites
- Récompenses obtenues : Nombre de récompenses obtenues grace aux quêtes
- Publications : Nombre de commentaires sur tous les threads (news, events, suggestions, etc)
- Vues du profil : Nombre de vues de la page par les autres joueurs authentifiés

### Derniers visiteurs

<img width="416" alt="screenshot_2242" src="https://user-images.githubusercontent.com/1420867/89585113-91dce900-d83d-11ea-92c0-9cb32c04c414.png">

Les 5 derniers visiteurs les plus récents, du plus récent au plus ancien
=> On affiche la liste complète qui correspond au quanti du "Vues du profil" ?

### Activités récentes

Récupération des commentaires récents agrégés, toutes catégories confondues, triés du plus récent au plus ancien, paginé par liste de 5 
**Attention** On n'affiche pas les réactions sur les threads internes tels que les commentaires sur les candidatures, les récupérations et les tickets.

**Comment by joshwhedon** [comment]
On met rien au sujet des votes dans les statistiques ? Genre les recompenses obtenues et nombre de votes a vie ?

**Comment by joshwhedon** [comment]
Sinon, vu que de toute facon je vais devoir charger tous les personnages, tu veux un encart pour voir plus de persos que les 4 top ?

**Comment by joshwhedon** [comment]
Le compte de visiteurs, c'est les visiteurs uniques ou totaux ?

**Comment by joshwhedon** [comment]
Question sur le type de compte. Sont-ils cumulables ? Est-ce qu'un mvp peut aussi etre vip ? Ou un mvp a les memes acces que vip avec des acces en plus ?

**Comment by joshwhedon** [comment]
Aussi, je comprends pas trop pourquoi il y a une differentiation entre nombre de quetes accomplies, et nombre de recompenses obtenues, ce sera tout le temps la meme valeur, vu que toutes les missions auront une recompense quelconque.

**Comment by Endalaust** [comment]
Remplaçons récompenses obtenues par "Votes à vie"
Moi j'aime bien l'idée de liste tous les personnages, mais côté joueur ils ne souhaitent pas, du tout. Ou à minima de pouvoir choisir de l'afficher ou non (même afficher les 4 ils sont pas chaud)
Le compte de visiteurs, j'ai indiqué authentifiés pour rester sur les visiteurs uniques auth, c'est plus pertinent qu'un compteur de clic sur l'url non?
Les types de comptes sont cumulables oui, avec une priorisation comme suit : 
MJ > VIP > MVP > Normal

**Comment by Endalaust** [comment]
La donnée userClass ne semble pas portée et interprétée 
La liste des profils ayant vu le profil est trié dans le mauvais sens, il faut du plus récent au plus ancien

**Comment by Endalaust** [comment]
+ titre du compte en title

**Comment by Endalaust** [comment]
Le rank est toujours affiché sur MJ, je sais pas trop pourquoi :/

**Comment by Endalaust** [comment]
On a des dates qui vont chier certains profils :(

```
2020-08-09 15:30:42,597 ERROR [http-nio-8084-exec-2] org.apache.juli.logging.DirectJDKLog: Servlet.service() for servlet [dispatcherServlet] in context with path [/api/web] threw exception [Request processing failed; nested exception is org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : [{"timestamp":"2020-08-09T13:30:42.589+0000","status":500,"error":"Internal Server Error","message":"Page size must not be less than one!","path":"/api/realm/characters/searches"}]] with root cause
org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : [{"timestamp":"2020-08-09T13:30:42.589+0000","status":500,"error":"Internal Server Error","message":"Page size must not be less than one!","path":"/api/realm/characters/searches"}]
```

**Comment by Endalaust** [comment]
Anticiper la pipe qui permet de faire un routerLink vers le profil sur toutes les pages à venir?

**Comment by joshwhedon** [comment]
LA pipe est deja preparee. Et je corrige le bug, c'est pas les dates j'ai juste pas pense aux comptes sans compte jeu.

**Comment by joshwhedon** [comment]
userRouting est la pipe.
