### ISSUE TITLE
Error 500 sur les pages du shop

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#150]
Tous les détails sont sur slack :(
Reproductible en preprod + local

**Comment by joshwhedon** [comment]
J'ai mis un timeout de 2 secondes sur l'appel d'aowow ca devrait eviter ce probleme.

**Comment by Endalaust** [comment]
Ca a réagit comment? Aowow est super lent étant sur son serveur pourri, les 2s c'est suffisant pour le joindre?

**Comment by Endalaust** [comment]
Testé en coupant le wifi, marche niquel; mais je reste soucieux de ma précédente remarque
