### ISSUE TITLE
Catégoriser les avatars

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#159]
La personnalisation semble plaire. 
Il faudrait pouvoir catégoriser les avatars et attribuer des permissions sur ces catégories. Exemples :

Catégories : 
- Héros
- Dieu très anciens
- Méca
- Gnomes
- VIP
- Maîtres de jeu
etc

Permissions : 
- Voir
- Pas voir
- Utiliser (déjà mis en place)
- Pas utiliser (déjà mis en place)

Exemples fonctionnels : 

- Je souhaite qu'un joueur puisse voir les catégories Héros, Dieu très anciens, Méca, Gnomes, et ne voit pas la catégorie VIP et Maître de jeu, et ne puisse choisir dans ces catégories que les avatars qui lui sont accessibles
- Je souhaite qu'un joueur VIP puisse voir les catégories Héros, Dieu très anciens, Méca, Gnomes, VIP, et ne voit pas la catégorie Maître de jeu, et ne puisse choisir dans ces catégories que les avatars qui lui sont accessibles
- Je souhaite qu'un Maitre de jeu puisse voir toutes les catégories, et choisir n'importe quel avatar

Les catégories seront affichées via les TABs angular

**Comment by joshwhedon** [comment]
Le backend et implemente et j'ai prepare les modeles et l'integration dans le front.
Ca utilise les autorites pour gerer l'acces. Du coup quand on aura le systeme de vip, les joueurs vip auront cette autorite qui leur donnera acces aux avatars.

**Comment by Endalaust** [comment]
C'est possible de faire un filtre comme sur "team" (https://way-of-elendil.fr/team) avec en guise de filtre les catégories, et que par défaut on affiche seulement la 1ere catégorie active (comme si par défaut sur team c'est "codir" qui était active, et il n'existe pas de All)?
J'aimerais m'en inspirer pour arrêter de te solliciter ensuite sur des thématiques similaires

**Comment by joshwhedon** [comment]
J'ai prepare cote client. C'est moche je te laisse mettre les classes qu'il faut mais ca marche.

**Comment by Endalaust** [comment]
Un joueur sans autorité peut voir les avatars mjs et les sélectionner, il ne devrait ni pouvoir faire l'un ou l'autre
