### ISSUE TITLE
Corrections après relecture site

### ISSUE THREAD

**Issue by Malyaa** [way-of-elendil/website#167]
Proposition de corrections des fautes/erreurs/oublis sur le nouveau site, vu avec Amandil.
Je traiterai la lourde partie events dans un deuxième temps, les corrections étant vraiment nombreuses et dans le soucis de ne pas surcharger le travail.

**_Corrections :_** Pas de liens de page (vu avec Amandil), je les ai si besoin.

Okay, vous n'avez pas voté jusqu'au bout (sur les sites de top vote) ces temps ci. 
Okay, vous n'avez pas voté jusqu'au bout (sur les sites de top vote) **ces temps-ci**. 

En votant pour nous, vous aidez Way of Elendil à garantir un flux stable de nouveaux joueurs permanent. 
En votant pour nous, vous aidez Way of Elendil à garantir un flux stable de nouveaux joueurs **permanents**. 

Toutefois, le fait de voter vous rend également éligibe à notre tombola mensuelle avec de nombreux lots à gagner ! 
**De surcroît**, le fait de voter vous rend également **éligible** à notre tombola mensuelle avec de nombreux lots à gagner ! 
(Ou **en outre**, **de plus** ou bien **qui plus est**)

À chaque fin de mois, les gagnants sont tirés au sort parmis les joueurs qui ont votés. 
À chaque fin de mois, les gagnants sont tirés au sort **parmi** les joueurs qui ont **voté**. 

Sans être dans le Top vous avez une chance d'être tiré au sort, toutefois plus vous votez plus vous avez de chance de gagner. 
Sans être dans le Top vous avez une chance d'être tiré au sort, **de surcroît**, plus vous votez plus vous avez de chance de gagner. 
(Ou **en outre**, **de plus** ou bien **qui plus est**)

Créez votre compte master dés maintenant pour associer vos anciens comptes World of Warcraft et en garder le contrôle !
Créez votre **Compte Master** **dès** maintenant pour associer vos anciens comptes World of Warcraft et en garder le contrôle!

Préparez vous pour l'aventure et creez votre compte World of Warcraft pour vous connecter au jeu!
Préparez vous pour l'aventure et **créez** votre compte World of Warcraft pour vous connecter au jeu!

Comment ca se passe pour les anciens joueurs ?
Comment **ça** se passe pour les anciens joueurs ?

Tout le monde va devoir créer un compte Master dés le 20 juillet 
Tout le monde va devoir créer un compte Master **dès** le 20 juillet 

Pour se faire, suivez simplement la procédure 
Pour **ce** faire, suivez simplement la procédure 

considérez vos comptes associés à ce mail comme perdu. 
considérez vos comptes associés à ce mail comme **perdus**. 

Tant de choses ont changées depuis votre départ... 
Tant de choses ont **changé** depuis votre départ... 

Les dates sont également consultables dans le tableau juste ci dessus. 
Les dates sont également consultables dans le tableau juste **ci-dessus**. 

différence de 150 points par rapport à votre cote d’équipe 
différence de 150 points par rapport à votre **côte** d’équipe 

A noter que seules les équipes qui ont jouées plus d'un match 
A noter que seules les équipes qui ont **joué** plus d'un match (X3)

Les niveaux d’armes et d’armure correspondants à votre niveau 
Les niveaux d’armes et **d’armures** correspondants à votre niveau 

L’apprentissage de tous les points de vol correspondant aux zones de votre niveau 
L’apprentissage de tous les points de vol **correspondants** aux zones de votre niveau 

les plans sont à acheter par vous même 
les plans sont à acheter par **vous-même** 

qui sera téléporté dés votre connexion 
qui sera téléporté **dès** votre connexion 

J'ai fais en sorte que les donjons soient similaire à des donjons de TLK 
J'ai **fait** en sorte que les donjons soient **similaires** à des donjons de TLK 

Vous pourrez par exemple obtenir des transmogrifications impossible à obtenir 
Vous pourrez par exemple obtenir des transmogrifications **impossibles** à obtenir 

mais aussi bien d'autre objet inédit comme des armes et set appartenant uniquement à des PNJ 
mais aussi bien **d'autres objets inédits** comme des armes et **sets** appartenant uniquement à des PNJ 

Et bien d'autres objets à transmo que je vous laisse découvrir par vous même. 
Et bien d'autres objets à transmo que je vous laisse découvrir par **vous-même**. 

De temps en temps sur Discord sera explicité quelques pages et quelques changements 
De temps en temps sur Discord **seront explicités** quelques pages et quelques changements 

Il va reste en ligne encore un moment 
Il va **rester** en ligne encore un moment 

c'est sur Discord que ca se passe 
c'est sur Discord que **ça** se passe 

disponible sur cette page Ou vous pouvez ouvrir une requête via World of Warcraft 
disponible sur cette page**. Ou** vous pouvez ouvrir une requête via World of Warcraft 

Gain d'expérience (quête, instance, mob), drop (gold, item) 
Gain d'expérience (**quêtes, instances, mobs**), drop (gold, **items**) 

Faites une requête en jeu sur un personnage du même compte en indiquant le maximum d’information 
Faites une requête en jeu sur un personnage du même compte en indiquant le maximum **d’informations** 

Connectez vous avec votre nom de compte World of Warcraft et non votre adresse mail 
**Connectez-vous** avec votre nom de compte World of Warcraft et non votre adresse mail 

Si ce n'est pas le cas, Cliquez droit sur le dossier puis "extraire". 
Si ce n'est pas le **cas, cliquez** droit sur le dossier puis "extraire". 

vous avez peut-être déplacé WoW.exe hors du dossier en voulant crée un raccourci 
vous avez peut-être déplacé WoW.exe hors du dossier en voulant **créer** un raccourci

Il suffit de remettre le WoW.exe dans le dossier du jeu et cliquez droit sur WoW.exe, puis raccourci. 
Il suffit de remettre le WoW.exe dans le dossier du jeu et **cliquer** droit sur WoW.exe, puis raccourci

Maître de jeu 
**Maîtres** de jeu

Changez le pseudonyme sous lequel les autres vous voit sur le site 
Changez le pseudonyme sous lequel les autres vous **voient** sur le site 

Les actualités du serveur publiés sur la page d'accueil 
Les actualités du serveur **publiées** sur la page d'accueil 

votre compte finira par être suprimé de manière irrévocable et définitive. 
votre compte finira par être **supprimé** de manière irrévocable et définitive. 

Comptes crées
Comptes **créés**

**_Mots trouvés plusieurs fois :_** 

Hotel
**Hôtel**
https://way-of-elendil.fr/
https://way-of-elendil.fr/news/4-le-compte-master-:-comment-ca-marche%253F

**Tombola** est écrit parfois avec une majuscule, parfois sans.
https://way-of-elendil.fr/vote

**Compte Master** est écrit parfois avec une majuscule, parfois sans.
https://way-of-elendil.fr/
https://way-of-elendil.fr/account/register
https://way-of-elendil.fr/news/4-le-compte-master-:-comment-ca-marche%253F
https://way-of-elendil.fr/return
https://way-of-elendil.fr/account/register
https://way-of-elendil.fr/news/2-way-of-elendil-v6-en-preparation
https://way-of-elendil.fr/game/faq
https://way-of-elendil.fr/account/preferences
https://way-of-elendil.fr/start
https://way-of-elendil.fr/news

**Horde et Alliance** sont parfois écrits avec une majuscule, parfois sans.
https://way-of-elendil.fr/
https://way-of-elendil.fr/game/statistics
https://way-of-elendil.fr/events
https://way-of-elendil.fr/shop/services

wow
**WoW**
https://way-of-elendil.fr/news/4-le-compte-master-:-comment-ca-marche%253F (X2)
https://way-of-elendil.fr/account/preferences

discord est écrit parfois avec une majuscule, parfois sans.
**Discord**
https://way-of-elendil.fr/news/4-le-compte-master-:-comment-ca-marche%253F
https://way-of-elendil.fr/game/faq

**_Incohérences :_** 

**blizzlike** est écrit parfois avec une majuscule, parfois sans.
https://way-of-elendil.fr/game/faq

Le compte master, dit compte maître. 
https://way-of-elendil.fr/news/4-le-compte-master-:-comment-ca-marche%253F
**Majuscules à Compte Maître ainsi qu’à Compte Master ?**

**_Maladresses ?_**Pas de liens de page (vu avec Amandil), je les ai si besoin.

Profitez d'un bonus d'expérience jusqu'au niveau 60 en renseignant son nom lors de votre inscription. 
Profitez d'un bonus d'expérience jusqu'au niveau 60 en renseignant **le nom d’un parrain** lors de votre inscription. 

une fois fait il vous suffit d'aller dans vos préférences 
une fois **fait, il** vous suffit d'aller dans vos préférences 

que vous pouvez échanger ensuite à Auzin et Lily, un autre marcheur du temps situé juste à coté de Cupri. Celui-ci vous proposera en échange plusieurs récompenses différentes 
que vous pouvez échanger ensuite à Auzin et Lily, **deux autres marcheurs du temps situés** juste à coté de Cupri. **Ceux-ci vous proposeront** en échange plusieurs récompenses différentes 

nous recrutons un reponsable communication pour diverses missions 
nous recrutons **un/une** reponsable communication pour diverses missions 

un condensé de toutes les nouvelles majeures vis à vis du serveur 
un condensé de toutes les nouvelles majeures **à propos** du serveur 

Invitez un ami à jouer ensemble ce qui associera vos comptes et vous permettra de bénéficier ensemble 
Invitez un ami à jouer **avec vous**, ce qui associera vos comptes et vous permettra de bénéficier ensemble 

Vous pouvez jouer gratuitement à World of Warcraft sur notre serveur mais vous avez la possibilité de découvrir le royaume par vous même du niveau 1 à 80, ou de commencer l'aventure directement au niveau maximum avec une récupération!
Vous pouvez jouer gratuitement à World of Warcraft sur notre serveur, **vous avez ainsi la possibilité** de découvrir le royaume par vous même du niveau 1 à 80, ou de commencer l'aventure directement au niveau maximum avec une récupération!

**Comment by joshwhedon** [comment]
Merci, j'ai corrige toutes les erreurs qui sont sur le site lui meme, il reste les erreurs dans les news et la description du job.

**Comment by joshwhedon** [comment]
News et job mis a jour. Par contre je touche pas a l'event de kreator.

**Comment by Malyaa** [comment]
Quelle efficacité, bon j'avais un pari en cours avec Amandil mais bon t'es trop rapide!

**Comment by KreatorWoE** [comment]
Fix pour la partie évent qui a été relevée aussi.
