### ISSUE TITLE
page récuperation

### ISSUE THREAD

**Issue by hermes-gm** [way-of-elendil/website#168]
Un level 80 qui n’apparaît pas sur la page de la récupération.

sur la récupération https://way-of-elendil.fr/admin/game/transfers/11986-lousbinette

J'ai fais un ip actions sur l'ip " 93.22.149.48" qui apparaît dans dernière ip de login

 Et je trouve le compte https://way-of-elendil.fr/admin/game/accounts/143639

avec un 80 mais ce 80 n’apparaît pas sur la demande de récupération.

**Comment by joshwhedon** [comment]
Une modif sera passee, j'ai retravaille un peu la recherche, faudra me dire si c'est mieux ou pire.

**Comment by hermes-gm** [comment]
Ça à l'air bon mais on va continuer à faire une double vérification en manuelle.

**Comment by hermes-gm** [comment]
En faite non c'est pas bon.
Je n'ai qu'une partie des personnages 80 liés à l'ip.
Je viens de refaire un compte master pour refaire une récup pour l'autre bug que j'ai remonté sur les recuperations.

En lien avec mon ip je n'ai pas tous mes level 80 qui apparaissent, juste ceux d'un compte.

Je sais pas trop comment vous aidez je reste à votre disposition pour toute demande complémentaire pouvant vous aider

**Comment by joshwhedon** [comment]
Tu parle de quelle ip ? Derniere ip de connection au compte ? Ip dans les actions de login ? Etc ? Parce que actuellement ce que le script fait c'est:
- il prend la liste de toutes les ips (ip du transfert sur le site, derniere ip du compte du transfert, les X dernieres ip des logs ip actions), les ip des comptes associes au compte master
- il prend la liste de tous les comptes qui ont ces ip en derniere ip et la liste de tous les personnages sur ces comptes

**Comment by Endalaust** [comment]
Suite au point de ce soir, présentement le soucis n'a pas été re rencontré
Je réouvrirai en cas de signalement
