### ISSUE TITLE
non accès à "mon compte" suite à un refus de récupération

### ISSUE THREAD

**Issue by hermes-gm** [way-of-elendil/website#169]
Un joueur à qui on a refusé sa récupération ( https://way-of-elendil.fr/admin/game/transfers/11986-lousbinette ( le compte à été ban en route pour une autre raison) )n'a plus accés a " mon compte " sur le site.

J'ai créé un nouveau master compte, un nouveau compte wow et un nouveau level 1( https://way-of-elendil.fr/admin/game/transfers/11987-melauzra ) j'ai refusé la demande et je n'ai plus accès à mon compte en cliquant en haut à droite non plus :

https://cdn.discordapp.com/attachments/502355663914008577/735165549956300890/unknown.png

En revanche j'ai accés à " mes comptes wow " et au reste du site.

**Comment by joshwhedon** [comment]
J'ai pousse un correctif mais j'ai pas assez d'info pour savoir si c'est reellement le probleme. A voir une fois mis en place.

**Comment by Endalaust** [comment]
@hermes-gm tu peux retester stp?

**Comment by joshwhedon** [comment]
J'ai repasse un autre correctif, je crois avoir trouve le probleme cette fois. Merci de retester au prochain deploiement.

**Comment by hermes-gm** [comment]
Alors j'ai refais un compte master, j'ai refais une demande de récupération, je l'ai refusé et j'en arrive au même point de ne pas accéder à mon compte mais bien au reste.

https://cdn.discordapp.com/attachments/502355663914008577/735566321923784785/unknown.png

**Comment by Endalaust** [comment]
Constat : Soucis d'acces côté API

Pour reproduire sans s'emmerder : Dupliquer une ligne et la mettre sur son compte master + compte jeu sans autorités associées, constater en allant sur overview
```
INSERT INTO `account_character_transfer` (`id`, `account`, `type`, `status`, `created_time`, `updated_time`, `updated_by`, `email`, `url`, `screenshot_url`, `reason`, `comment`, `feedback`, `ip`, `character`, `server_account`, `server`, `first_profession`, `second_profession`) VALUES
('2', '21', 'Private', 'Completed', '2020-07-14 11:39:47', '2020-07-14 11:42:09', '16', 'hermes_gm@gmail.com', 'https://www.paragon-servers.com/', 'https://screens.way-of-elendil.fr/gook8RIG.PNG', 'lettre de motivation', NULL, NULL, '176.149.115.57', '451260', '7665', '1', '182', '171');
```
