### ISSUE TITLE
Pouvoir réactiver les comptes désactivé

### ISSUE THREAD

**Issue by hermes-gm** [way-of-elendil/website#171]
Pour le moment on ne peut pas réactiver les master compte ayant été désactivés par les joueurs, serait il possible d'ajouter un truc sur le site pour que l'on ai tous accès à cette fonctionnalité.

**Comment by Endalaust** [comment]
Attention : Les comptes jeux sont aussi banni sur un selfban, non gérable par un mj via la commande unban
Il faut intégrer cette procédure en plus

**Comment by joshwhedon** [comment]
Je suis pas d'accord avec ca. Si un joueur desactive son compte, on ne devrait pas pouvoir le reactiver. C'est le choix du joueur, il connaissait les risques.

**Comment by Endalaust** [comment]
On a quand même un problème, quand un joueur s'auto ban on a présentement aucun moyen de le deban 
Je passe par la DB pour changer le statut

Je ne sais pas s'il existe une commande pour ce cas spécifique :(

**Comment by joshwhedon** [comment]
Non il y a pas de commande pour. Il faut changer dans la db. Mais la n'est pas le probleme. Je ne suis pas certains qu'il soit acceptable pour nous de debloquer des comptes qui ont ete "supprimes" par les joueurs.

**Comment by Endalaust** [comment]
C'est une demande assez récurrente en fait
Les joueurs se pointent des mois ou des années plus tard avec cette demande

Avec le nouveau site, les gens qui lisent pas le provoquent aussi
On peut bouger le besoin côté joueur mais ca implique une page spécifique

**Comment by joshwhedon** [comment]
Mouai. Ca me semble encore pire comme idee :D . Bref, je mettrai un bouton demain.
