### ISSUE TITLE
Ajouter le ban de compte master dans les options du compte master pour l'autorité staff

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#172]
En tant que maître de jeu
Je souhaite avoir un bouton ban sur l'interface de gestion du compte master en renseignant un motif
Afin de bannir le compte master + bannir tous les comptes wow associés 
Et que le joueur soit automatiquement kick de sa session sur le compte master (actuellement pas le cas)

**Comment by joshwhedon** [comment]
ALTER TABLE `account` ADD `banned` TINYINT(3) NOT NULL DEFAULT '0' AFTER `enabled`, ADD `ban_reason` VARCHAR(255) NULL DEFAULT NULL AFTER `banned`;
ALTER TABLE `account` ADD `ban_date` TIMESTAMP NULL DEFAULT NULL AFTER `ban_reason`;
3 champs ajoute.
