### ISSUE TITLE
Limiter l'envoi de mails sur un même type de mail

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#173]
Pour chaque type de mail liés au compte je veux un cooldown de 12h pour pouvoir en envoyer un autre du même type.

Tous les cas seront gérés avec une alerte : Une demande de ce type est déjà en cours. Veuillez ré-essayer plus tard

Sont concernés : 

1. Game account linked 
2. Master account lost password
3. Master account add new email :
4. Master account change primary email 

Ne sont pas concernés : 

5. Don d'item à un compte jeu sans compte master
6. Application accepted
7. Application refused

**Comment by joshwhedon** [comment]
Link de compte : verification faite sur l'id du compte jeu (reference dans email_history)
Autres : verification faite sur l'id du compte site (sent_to dans email_history)

**Comment by joshwhedon** [comment]
woe.mail.quota.interval nouvelle config sur auth server, interval en minute, par defaut 720 (12 heures)
J'ai aussi ajoute un champ server a email_history
