### ISSUE TITLE
Discord : Canaux de guilde

### ISSUE THREAD

**Issue by joshwhedon** [way-of-elendil/website#177]
Donner la possibilite aux joueurs de communiquer avec leur guilde en jeu.

Questions:
- Limite aux guildes dont le chef est VIP
- Comment le canal se cree-t-il ? Via une commande du chef de guilde VIP ? Via un bouton sur le site ? Automatiquement (mais comment ?
- Comment les joueurs obtiennent-ils acces au canal ? Via commande du joueur ? Automatiquement quand le joueur rejoint le serveur / le chef de guilde ouvre le canal ?

**Comment by joshwhedon** [comment]
La facon dont je le vois, l'ideal serait probablement:
- une page pour que les chefs de guilde puissent gerer si leur guilde apparait ou non sur discord (peut etre a faire en combinaison avec https://github.com/way-of-elendil/website/issues/146).  Probablement juste un radio button.
- une page pour que les joueurs puissent gerer sur quel canaux de guilde ils veulent etre invites (parce que un joueur ne voudra pas forcement que tout le monde sache qui il est sur discord / etc). Je suppose que sa liste de guilde avec un toggle sur chaque guilde irait. Une alternative serait de le faire via une commande discord.

Apres, il faudra mettre en place un mechanisme de synchronisation, peut etre journalier, pour retirer les droits des joueurs qui ne sont plus dans la guilde.

**Comment by Endalaust** [comment]
J'ignore un peu comme les bots marchent mais via une interface web on peut faire ce genre de configuration. Maintenant j'ignore la complexité que ca engendre
Exemple :
<img width="634" alt="screenshot_2127" src="https://user-images.githubusercontent.com/1420867/88425667-0cdee200-cdf0-11ea-960a-4da10f55f32a.png">

### Proposition de paramétrage côté joueur 

Maintenant les pratiques les plus simples sont en général à base de commande : 

1. On invite le bot sur le serveur
2. On tape la commande !woe guild add ID 
3. Retour du bot :
3.1 OK : La guilde NAME est maintenant connectée à ce serveur ! Sur quel canal souhaitez-vous voir le chat ?
3.2 KO : Désolé mais vous n'êtes pas le maitre de la guilde de NAME, vous ne pouvez pas faire cela !
4. Le joueur saisi le canal #canal 
5. Le bot confirme : Le canal #canal est désormais connecté à votre chat de guilde !
Démarrage du flux

### Commandes proposées, accessibles seulement au guild master: 

!woe guild add ID => Permet de lancer l'association de la guilde au serveur discord
!woe guild delete ID => Permet de supprimer l'intégration de la guilde au serveur discord

Exemple : 

<img width="853" alt="screenshot_2128" src="https://user-images.githubusercontent.com/1420867/88425921-85de3980-cdf0-11ea-91e0-38b802fed664.png">

Le delink du serveur discord doit également être présent sur le site en cas de problèmes sur le serveur discord, le GM doit être en capacité de supprimer l'intégration de la guilde à un serveur discord via le site.

### Acces au canal de guilde Discord

Pas notre problème, au GM de configurer les restrictions de son choix au canal au bot et à ses membres sur Discord.

### Interaction des membres 

Par défaut un utilisateur sur Discord peut lire tous les messages qui viennent du jeu, il n'y a pas de filtre du contenu en provenance du jeu.
En revanche pour pouvoir répondre via Discord, je suggère comme dit ensemble aujourd'hui le concept de booster de guilde pour lui faire atteindre un certain palier qui octroie l'interaction. 

Pas de paramétrage spécifique joueur par joueur pour vérifier qu'ils peuvent ou non poster... Exemple : Un random sur le serveur discord, s'il a les bons droits via le serveur discord, pourra interagir avec le jeu.

### Particularités 

Je propose de ne pouvoir faire qu'une seule association par guilde à Discord. 
!woe guild add ID => Désolé mais cette guilde a déjà été associée à un serveur Discord. Si vous voulez la dissocier pour l'associer à un nouveau serveur, rendez vous sur la page de configuration du bot Way of Elendil : https://way....

**Comment by joshwhedon** [comment]
OK, si tu veux vraiment envoyer le bot sur d'autres serveurs, faut que je fasse un autre bot. Parce que je veux vraiment pas exposer le bot avec toutes les fonctionnalites actuelles, sur un autre serveur.

**Comment by joshwhedon** [comment]
Sinon, tu te rends compte qu'avec ton mechanisme, seul le guild leader aura besoin de lier son compte discord ?

**Comment by joshwhedon** [comment]
https://way-of-elendil.fr/suggestions/4-flux-de-guilde

**Comment by joshwhedon** [comment]
Changement au niveau des commandes : 
!woe guild channel add #idedlaguide
!woe guild channel remove #idedelaguilde
!woe guild officer channel add #idedelaguilde
!woe guild officer channel remove #idedelaguilde

Les commandes d'ajout doivent etre faites dans le canal ou le canal doit etre lie.

**Comment by Endalaust** [comment]
<img width="1680" alt="screenshot_2366" src="https://user-images.githubusercontent.com/1420867/91203641-84f83a80-e703-11ea-8237-15225dea1265.png">

Pour envoyer un item du compte master au jeu en activant le bot de guilde

**Comment by Endalaust** [comment]
Sinon, les commandes ont l'air de moyennement marcher
Le guild add ne me renvoie jamais un retour positif
Voir le canal guild sur Discord dans la rubrique staff
On en reparle demain

**Comment by joshwhedon** [comment]
parce que c'est pas guild add ?

**Comment by Endalaust** [comment]
Suite au premier déploiement en test avec une guilde, les 4 remontées sont les suivantes : 

- Le canal officier sur Discord  transmet également au canal Général; idem côté jeu, le canal officier jeu transmet sur le canal Général Discord

- Les checks et alertes du bot : Si j'ajoute le bot sur un premier canal discord, tout est OK. J'ajoute le bot sur 2nd canal discord (officier), les checks+alertes sont désormais exclusivement sur ce 2nd canal
=> Check = vérifier que le compte discord est auth et autorisé

- Dans le cas précédent, on arrive donc sur un canal initial discord sur lequel n'importe qui peut communiquer avec la guilde (plus de checks ni d'alerte sur compte non autorisé / non authentifié)

- Suite à un delete des canaux via commandes + une suppression en base de mon côté, le GM a refait un add sur ses canaux et le pont était fonctionnel (je suppose que c'est lié au cache). Sa guilde n'a pas été réinjectée en base.
Au redémarrage du service, plus rien ne marchait, il a fallu refaire les commandes add (ce qui a eu pour effet de réinjecter en base cette fois)
