### ISSUE TITLE
Discord : Login avec Discord

### ISSUE THREAD

**Issue by joshwhedon** [way-of-elendil/website#178]
Afin de pouvoir supporter plusieurs features liees a discord, il faut rendre possible de se connecter avec Discord, et de lier son compte discord a son compte master.

**Comment by Endalaust** [comment]
Possible de me fournir les credentials du bot prod?
J'ai fini le redesign du login + link

**Comment by joshwhedon** [comment]
Je donne ca sur slack quand tu es connecte.
