### ISSUE TITLE
Purger les comptes wow sans personnages

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#180]
Prévoir un CRON qui supprime les comptes World of Warcraft qui n'ont jamais été utilisés (attention aux champs de realm, j'ai peur qu'on ait des datas de merde et qu'il faille double check, exemple : last_login = null AND characters not found where account = name)

Je propose cette purge tous les 7 jours
Avec le bug https://github.com/way-of-elendil/website/issues/179 on a déjà plus de 150 comptes crées pour rien

**Comment by joshwhedon** [comment]
On a un total de 30 000 comptes sans personnages. 7 jours me parrait court par contre, je prefererai un mois. 
Maintenant, qu'est-ce qu'on supprime ? Uniquement le compte, ou bien on vide aussi les tables de contenus associes ?
Personnellement, je prefererai peut etre nous limiter dans un premier temps aux comptes qui ne sont jamais connectes, qui representent 17 000 comptes (sur les 30 000).
