### ISSUE TITLE
Image : Les alts ne s'affichent pas

### ISSUE THREAD

**Issue by joshwhedon** [way-of-elendil/website#182]
https://way-of-elendil.fr/events/5-assauts-du-fleau Dans le code html, les images on un alt, mais il apparait pas quand on met la souris dessus. Normal ou pas ?

**Comment by Endalaust** [comment]
Normal. Au hover, il faut mettre une balise title=""
Le alt="" permet 2 choses : 

- Indiquer le contenu de l'image à un robot
- Afficher le contenu de alt si l'image ne peut pas s'afficher

**Comment by joshwhedon** [comment]
JE dis a Kreator.
