### ISSUE TITLE
Emails sender non reset 

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#183]
Le compteur sur le site affiche le nombre de mails envoyés depuis la dernière maj du service, il n'y a plus de reset à minuit
Présentement on a plus de 200 mails envoyés répartis sur 3 jours il me semble, j'ignore si arrivée à 480 on va finir par switcher sur un 2nd mail ou non

Comportement attendu : On reset tous les jours le compteur et on repart sur le 1er mail de la liste en sender

**Comment by joshwhedon** [comment]
J'ai mis a jour les crons, a voir.

**Comment by Endalaust** [comment]
Pas de reset :( 
Ca se reset uniquement quand je met à jour le service

**Comment by joshwhedon** [comment]
J'ai remis une modif.
