### ISSUE TITLE
explication outils donjon aléatoire

### ISSUE THREAD

**Issue by Babyface-187** [way-of-elendil/website#185]
ajout d'une question/réponse sur la page https://way-of-elendil.fr/game/faq dans la section Royaume de jeu / les questions sur le jeu : 

l'explication du fonctionnement de l'outils donjon et de pourquoi ça ne proc pas. 

Tous les jours il y a des joueurs qui pensent/disent aux autres que l'outils bug.
 l'ajout d'une question/réponse sur cette page nous faciliterais la tâche, juste besoin de copy/paste le lien au joueur. 
Une réponse du style que tu avais faites Josh, sur le forum, qui explique bien le pourquoi du comment

**Comment by Endalaust** [comment]
![Uploading screenshot_2169.png…]()

Ajouté
