### ISSUE TITLE
Notifications 

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#186]
Quand on poste une réponse à un fil de discussion dans suggestions que je suis, je n'ai pas la notification qui pop
En revanche si je vais dans mes notifications, j'ai bien la notif dans le bloc "plus anciens" (en mode lu)

**Comment by joshwhedon** [comment]
Et la date de la notification a ete mise a jour ? Ou c'est juste l'ancienne ?

**Comment by Endalaust** [comment]
Date à jour
