### ISSUE TITLE
Impossible de quitter la page buy-woellars

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#187]
Je me rends sur la page d'achats de crédits
Je ne peux pas cliquer sur un lien du menu, je suis stuck sur la page 
Au clic sur un lien du menu j'ai l'erreur console suivante:

<img width="1790" alt="screenshot_2171" src="https://user-images.githubusercontent.com/1420867/88981160-acefac00-d2c5-11ea-80a7-09626e1f6d91.png">

**Comment by joshwhedon** [comment]
Devrait etre regle.
