### ISSUE TITLE
Changer le Slider

### ISSUE THREAD

**Issue by KreatorWoE** [way-of-elendil/website#188]
Faudrait ajouter une fonctionnalité pour qu'on puisse modifier le slider comme sur l'ancien site si possible.

Thx !

**Comment by Endalaust** [comment]
@joshwhedon

**Création d'une slide** 

- Le texte du bouton n'est pas enregistré

**Update d'une slide :** 

- Place de la slide ne se met pas à jour
- Le texte du bouton n'est pas enregistré

**Cas particulier :** 

Je publie une slide en url, je l'édite, j'enlève l'url et je met un routerLink, la slide ne se met pas à jour et je conserve mon url.

**Comment by joshwhedon** [comment]
Ca devrait etre corrige.
