### ISSUE TITLE
Offrir à un ami

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/website#192]
**Describe the bug**
Le joueur Akunadin a voulu offrir au joueur Shàvøk un changefaction. (ce sont les noms des personnages joueurs)

Shàvøk a pour compte master Shavok, Akunadin a voulu envoyer le changefac sur le compte master de Shàvøk : Shavok.
Sauf qu'il y a un joueur et un compte du nom de Shavok, le cadeau a été envoyé via l'email du compte joueur Shavok du coup

1. J'ai redonné le changefac au personnage Shàvøk, il y a un changefac a enlever sur l'email 
jerome_gaudre@hotmail.com
=> Possibilité de faire quelque chose pour ça ? je crois pas qu'on ait accès à quoi que ce soit pour rendre invalide ce cadeau

2. Akunadin a pu avoir l'affichage de l'email du compte Shavok sans qu'il ne connaisse ni d'eve ni d'adam ce joueur

(screen d'Akunadin depuis son compte)
<img width="1157" alt="Capture d’écran 2020-08-08 à 13 20 16" src="https://user-images.githubusercontent.com/60295792/89709003-37967200-d97c-11ea-9ec0-ab46a7eb814e.png">

**Comment by Endalaust** [comment]
Soucis d'interprétation de la modal.. Le mec sait pas lire :(
