### ISSUE TITLE
Page historique des arènes

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#195]
Créer une page publique qui liste les arènes, résultats etc, mais pas les IPs des joueurs

**Comment by joshwhedon** [comment]
Si on utilise le meme design que la page de l'historique de matchs par team, je peux faire ca rapidement moi meme et tu auras juste a ajuster un peu.
Aussi, tu veux le mettre ou ? Dans la section pvp ?

**Comment by joshwhedon** [comment]
J'ai push l'integration.

**Comment by Endalaust** [comment]
Suggestion côté joueur : Ajouter la map sur chaque match

**Comment by joshwhedon** [comment]
On peut, je te laisse faire la page j'ajouterai apres.

**Comment by Endalaust** [comment]
C'est juste rajouter la donnée dans le titre de l'accordéon, mais je sais pas si on a pas trop de données avec ça. Je testerais ce soir

**Comment by Endalaust** [comment]
Fuck off

**Comment by Endalaust** [comment]
Ah bah non on s'en bat plus les couilles
