### ISSUE TITLE
Statistiques : Filtre les classes par [80/all]

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#196]
https://way-of-elendil.fr/game/statistics

<img width="822" alt="screenshot_2287" src="https://user-images.githubusercontent.com/1420867/89947653-1ad09780-dc25-11ea-9892-3dbcfcdd0310.png">
Ajout d'un filtre : 

- Tous niveaux
- 80

Par défaut le filtre est sur "tous niveaux"

**Comment by joshwhedon** [comment]
C'est integre
