### ISSUE TITLE
Erreur 500 lors de résolution requête

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/website#198]
Lors de la résolution de requête via le complete, on arrive parfois sur une erreur 500
![image](https://user-images.githubusercontent.com/60304524/90545747-676a2480-e189-11ea-9aee-06fe712579c4.png)

Je n'ai pas pu reproduire à 100% mais de ce que j'ai cru remarquer cela survient quasiment tout le temps lors de requête venant de personnages ally 80 et seulement quelques fois pour le reste des personnages.

**Comment by joshwhedon** [comment]
Corrige prochaine maj du site.
