### ISSUE TITLE
Arena team : Historique, pagination

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#201]
https://way-of-elendil.fr/armory/arena/2322-ez-games/activity 

L'historique est limité à 20 matchs
Peut on rajouter tout l'historique avec une pagination par tranche de 20?

**Comment by joshwhedon** [comment]
Quit a paginer le mets un historique de 10, ca evitera de trop charger pour rien, et ca couvrira probablement la majorite des cas. Aussi, avoir besoin de scroller dans une page c'est pas top. On augmentera si on a du feedback.
C'est push
