### ISSUE TITLE
Suggestions : Refonte de la "tendance"

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#203]
Actuellement
tendance = nombre de votes sur un mois, classés par quantité descendante 

Souhait
tendance = nombre de commentaires par semaine

Pertinent?

**Comment by joshwhedon** [comment]
On peut aussi combiner les 2.

**Comment by joshwhedon** [comment]
C'est push, tendance = votes de la semaine + (commentaires de la semaine * 3)
