### ISSUE TITLE
Arena history : Team delete = error

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#207]
https://way-of-elendil.fr/armory/arena/2308-cuilliere-de-bois/activity

Certains matchs ont eu lieu contre une équipe que je suppose delete, sans réussir à récupérer le nom de l'équipe ca plante

<img width="1381" alt="screenshot_2343" src="https://user-images.githubusercontent.com/1420867/90804686-dcb92f00-e31a-11ea-93f8-529659f3c02b.png">

<img width="1792" alt="screenshot_2342" src="https://user-images.githubusercontent.com/1420867/90804634-cb702280-e31a-11ea-9a6b-b1911de3204a.png">

**Comment by joshwhedon** [comment]
Quel est le comportement attendu ? On remplace le nom de l'equipe avec Equipe supprimee ou un truc du genre ?

**Comment by Endalaust** [comment]
Oui désolé j'ai oublié de le préciser
=> Equipe supprimée
