### ISSUE TITLE
Bug missions de site

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/website#209]
Ci après seront regroupés les bugs au niveau des quêtes de site : 
- mission 0/1
Monter de niveau au dela du niveau 10      
LevelUp
![image](https://user-images.githubusercontent.com/60304524/91220970-440d1f80-e71d-11ea-9512-bcf1f9df9d65.png)
=> Non comptabilisé

**Comment by joshwhedon** [comment]
Au dela du niveau dix. Tu es passe niveau 11 apres ?

**Comment by Amilgaull** [comment]
Oui j'étais niveau 11
