### ISSUE TITLE
Don à un ami

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#210]
**Describe the bug**
Le don à un ami renvoie une 400 au clic sur le CTA

**To Reproduce**
1. Se connecter sur un compte JOUEUR
2. Offrir à un ami un objet
3. Choisir n'importe quel pseudo existant

**Screenshots**

<img width="1509" alt="screenshot_2368" src="https://user-images.githubusercontent.com/1420867/91222423-715acd00-e71f-11ea-94ea-e37280b4cb0c.png">
<img width="1670" alt="screenshot_2367" src="https://user-images.githubusercontent.com/1420867/91222432-761f8100-e71f-11ea-87ee-3055e15767fa.png">

**Comment by Endalaust** [comment]
Ce bug n'est pas reproductible sur un compte scopé staff.
Je ne reproduis pas non plus via l'envoi par email, mais visiblement d'autres joueurs ont le même soucis par email

J'essaye de reproduire.

**Comment by Endalaust** [comment]
Pour info on accumule les demandes de support sur ce sujet @joshwhedon  :(

**Comment by joshwhedon** [comment]
Corrige
