### ISSUE TITLE
Erreur armurerie : recherche avec caractère spécial

### ISSUE THREAD

**Issue by Malyaa** [way-of-elendil/website#213]
L'armurerie retourne une erreur en fonction du nom que l'on recherche.
L'erreur est provoquée par la recherche de guildes.

**To Reproduce**
1. Aller sur https://way-of-elendil.fr/armory
2. Faire une recherche avec pour nom "ẞẞ" (tout nom avec ce caractère provoque l'erreur)
3. Valider la recherche
4. Admirer la page https://way-of-elendil.fr/server-error
On constate que la liste des personnages a brièvement le temps de s'afficher avant le passage sur la page d'erreur.
L'erreur vient en fait de l'appel à la recherche de guildes :
https://realm.way-of-elendil.fr/api/realm/guilds?size=20&page=0&name=%E1%BA%9E%E1%BA%9E
En remplaçant par un paramètre name "aa" par exemple, on récupère bien des données.

**Expected behavior**
Pas d'erreur, mais affichage de la liste des personnages.

**Additional context**
Le problème est indépendant de l'existence ou non d'un personnage ou d'une guilde ayant le nom mis dans la recherche : Le problème vient de la requête, pas du résultat.

**Comment by Endalaust** [comment]
2020-12-25 09:14:55,368 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper [http-nio-8082-exec-54] Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation 'like'

**Comment by Endalaust** [comment]
Fixé en production
