### ISSUE TITLE
IDs de raid : Masquer le groupe ouvert.

### ISSUE THREAD

**Issue by Ysya555** [way-of-elendil/website#217]
"Je suis frustrée" quand je clique sur "voir le groupe" de ne plus avoir de moyen de le masquer par la suite.
**Describe the solution you'd like*
Pouvoir masquer le groupe en appuyant de nouveau sur "voir le groupe".
De plus, lorsqu'on clique sur la flèche pour rétracter les infos raids, il faudrait que le groupe disparaisse également. Merci
![unknown](https://user-images.githubusercontent.com/77018709/106515632-3f237780-64d6-11eb-8dba-81db69514375.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Endalaust** [comment]
Fixé
