### ISSUE TITLE
Boutique : Visuels absents

### ISSUE THREAD

**Issue by Ysya555** [way-of-elendil/website#219]
Dans la boutique des familiers, il manque deux visuels : Clochette tintinnabulante et Bébé tigre blanc.
https://woehead.way-of-elendil.fr/?item=21308
https://woehead.way-of-elendil.fr/?item=23712

![fami](https://user-images.githubusercontent.com/77018709/106639078-de06ad00-6584-11eb-9d63-eb2e421f3c8c.png)

**Comment by Endalaust** [comment]
Ces visuels n'existent pas sur le site de Blizzard, pas de solution présentement

**Comment by Endalaust** [comment]
Fixé
