### ISSUE TITLE
Modification des accès de l'équipe

### ISSUE THREAD

**Issue by Babyface-187** [way-of-elendil/website#223]
**Describe the bug**
Impossible de modifier les accès des membres du staff via le site web

**To Reproduce**
1. Go to https://way-of-elendil.fr/admin/community/team
2. Click on 'Gérer' à droite
3. Modifier les accès, par exemple Staff + Account + Commands_rank_2
4. Click on 'Mettre à jour l'utilisateur'

**Expected behavior**
L'utilisateur devrait avoir les accès suivant : Staff + Account + Commands_rank_2
Or, une fois l'utilisateur mis à jour, les accès sont toujours : Account + Commands_rank_1 + Lead
Donc, peu importe les accès donnés ou retirés à l'utilisateur, une fois cliqué sur le bouton 'Mettre à jour l'utilisateur', il se retrouvera avec les accès mentionné ci-dessus. 

**Screenshots**

Droits donnés au nouveau MJ
![Capture d’écran 2021-02-25 à 16 15 56](https://user-images.githubusercontent.com/66620243/109174179-e36ea600-7784-11eb-90a6-aebbe6d55073.png)

Les droits qu'il reçoit après la mise à jour de l'utilisateur
![Capture d’écran 2021-02-25 à 16 16 03](https://user-images.githubusercontent.com/66620243/109174256-f7b2a300-7784-11eb-9fc6-2ac9069a395b.png)

**Comment by joshwhedon** [comment]
Seuls les admins peuvent retirer / donner le rang lead je crois

**Comment by Endalaust** [comment]
Fixé prochaine maj du site
