### ISSUE TITLE
Rafraichissement de page ticket

### ISSUE THREAD

**Issue by Babyface-187** [way-of-elendil/website#229]
**Describe the bug**
Quand on est sur un ticket depuis le site (ex : https://way-of-elendil.fr/admin/game/tickets/11111) et que l'on clique plus bas sur un autre ticket dans "Requêtes passées", l'url change bien vers le nouveau ticket, mais la page reste la même.

**To Reproduce**
1. Go to https://way-of-elendil.fr/admin/game/tickets/19166
2. Click on 'Requêtes passées' 19157
3. See error

**Expected behavior**
La page change vers le nouveau ticket.

**Screenshots**
Ci-dessous le ticket 19166
![Capture d’écran 2021-03-21 à 19 48 01](https://user-images.githubusercontent.com/66620243/111917118-8d88d780-8a7e-11eb-8a15-368bb363dd22.png)

Ci-dessous le ticket 19157
![Capture d’écran 2021-03-21 à 19 48 22](https://user-images.githubusercontent.com/66620243/111917132-a0031100-8a7e-11eb-9723-05889607c494.png)

**Desktop (please complete the following information):**
testé sur Chrome, Safari, Opera, Firefox

**Comment by Babyface-187** [comment]
refresh la fonctionne

**Comment by Endalaust** [comment]
Fixé prochaine release
