### ISSUE TITLE
Admin Tickets : Proposition de réponse par l'IA

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/website#251]
**En tant que** system
**Je souhaite** proposer une réponse automatique fournie par l'IA aux tickets
**Afin de** automatiser les réponses aux tickets dans un futur proche

# Business rules 

- Tous les tickets doivent inclure un bloc "Réponse par l'IA" 
- Pour une ticket à l'état "Opened" : La réponse au ticket doit être injectée à 2 endroits : Dans la réponse au joueur, et dans un champ dédié IA en bleu pour toujours avoir une comparaison entre le texte proposé et la réponse qui sera envoyée
- La question et la réponse doivent être enregistrée côté fournisseur (simple déclaration dans les paramètres d'envoi du POST avec `conversationId`)

# Backend

https://docs.chatbase.co/docs/getting-started
Voir avec @Endalaust pour la clé secrète API 
A chaque ouverture d'une page de ticket WEB, on appelle la route de l'IA pour lui soumettre la question et récupérer la réponse au format JSON

## Envoyer une question à l'IA 

Doc du POST : https://docs.chatbase.co/docs/message-a-chatbot
Exemple avec https://way-of-elendil.fr/admin/game/tickets/31493 

Paramètres : 

- **messages** : Bonsoir, le haut fait ' Lectures studieuses ' est il bugué svp? J'arrive devant les bouquins mais aucun rapport avec les bouquins, je connais pourtant des gens qui ont réalisé ce haut fait. 
- **chatbotId** : 0h2zN-M6CAkMOSKzQerK7
- **stream** : false
- **temperature** : 0.2
- **conversationId** : GUID du character
- **model** : GPT-4o

Response : 

```json
{
  "text": "Bonsoir ! Pour l'accomplir, vous devez trouver et lire 8 livres spécifiques à Dalaran, chacun d'eux apparaissant à un endroit précis. Ces endroits de spawn peuvent faire apparaître soit les livres du haut fait, soit d'autres livres aléatoires. Une fois qu'un livre est lu, il disparaît et est remplacé par un livre aléatoire. Si un autre joueur passe avant vous et lit le bon livre, vous devrez attendre qu'il réapparaisse."
}
```

# UI 

## Réponse proposée dans le champs "Reponse au joueur" + "Proposition de l'IA"

![Image](https://github.com/user-attachments/assets/96cdc153-2887-4e9c-a49e-6fb3998f80fa)

Le maître de jeu peut modifier la réponse et doit résoudre par lui même. Dans un temps 2 nous verrons pour totalement automatiser les réponses, sous réserve que les réponses soient cohérentes.

**Comment by AlexWayOfElendil** [comment]
intégration maquette ok, branche en cours : 'origin/feat/ai-ticket'

**Comment by Endalaust** [comment]
Rendu super en front, et fonctionnel 
A intégrer en back pour anticiper la suite :p

Quelques réflexions depuis : 

- Il serait pertinent de stocker dans une table indépendante le message retour de l'IA et de l'associer au ticket
- Il serait pertinent de n'appeler qu'une seule fois l'API et stocker la réponse, au lieu d'appeler l'API à chaque refresh de la page
- On anticipe la suite : Dans le service java il y a un trigger qui récupère chaque ticket lorsqu'il est ouvert en jeu. Demain, nous réagirons à ce trigger en envoyant la question à l'API et en récupérant la réponse pour cloturer automatiquement le ticket. Mais pas tout de suite, d'abords on reste sur ce mode avec une proposition de réponse et on laisse l'équipe assistance jauger de la pertinence des réponses.
